version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: affiliate-rewards-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: affiliate_rewards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: affiliate-rewards-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: affiliate-rewards-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/affiliate_rewards?schema=public"
      REDIS_URL: "redis://redis:6379"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "your-secret-key-here"
    depends_on:
      - postgres
      - redis
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:
  redis_data:

